<Project Sdk="Aspire.AppHost.Sdk/13.6.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>ssw-rules-rules-chat-apphost</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.6.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.6.1" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RulesChat.Database\RulesChat.Database.csproj" />
  </ItemGroup>

</Project>
