nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.1.cjs

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'
