steps:
- checkout: self
  clean: true
  fetchDepth: 1
  
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in env'
  inputs:
    targetFiles: .env.template
    escapeType: none
    tokenPrefix: '#{'
    tokenSuffix: '}'
    actionOnMissing: fail

- task: Cache@2
  displayName: Cache Yarn packages
  condition: and(succeeded(), eq(variables['ENABLE_YARN_CACHE'], 'TRUE'))
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
      yarn
    path: $(yarn config get cacheFolder)

- task: Cache@2
  displayName: Cache Gatsby .cache
  condition: and(succeeded(), eq(variables['ENABLE_GATSBY_CACHE'], 'TRUE'))
  inputs:
    key: 'gatsby_cache | "$(Agent.OS)"'
    restoreKeys: |
      gatsby_cache | "$(Agent.OS)"
    path: $(Build.SourcesDirectory)/.cache

- task: Cache@2
  displayName: Cache Gatsby public
  condition: and(succeeded(), eq(variables['ENABLE_GATSBY_CACHE'], 'TRUE'))
  inputs:
    key: 'gatsby_public | "$(Agent.OS)"'
    restoreKeys: |
      gatsby_public | "$(Agent.OS)"
    path: $(Build.SourcesDirectory)/public

- task: NodeTool@0
  inputs:
    versionSource: fromFile
    versionFilePath: .nvmrc

- script: yarn install --immutable
  displayName: yarn install

- script: |
    mv .env.template .env.production
    cat .env.production
  displayName: 'Rename env file'
  
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)/.azure/scripts/get-rule-history.ps1
    arguments: > # Use this to avoid newline characters in multiline string
      -AzFunctionBaseUrl $(AzFunctionBaseUrl)
      -GenerateHistoryFileFunctionKey $(GenerateHistoryFileFunctionKey)
      -outputFileName "history.json"
  displayName: 'Get Rule History JSON'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)/.azure/scripts/create-commits-history.ps1
    arguments: >
      -Token $(GITHUB_API_PAT)
      -GithubOrg $(GITHUB_Org)
      -GithubRepo $(GITHUB_Repo)
  displayName: 'Get History Commits of Each Contributor'
  
- script: GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true yarn build
  displayName: yarn build:incremental

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'public'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/public.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
