# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

schedules:
- cron: 0,30 0 * * *
  displayName: Scheduled CodeAuditor Test
  always: true

stages:
- stage: test
  displayName: Tests - CodeAuditor
  jobs:
  - job: Test
    steps:
    - template: templates/test.yml