# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: 0,30 * * * *
  displayName: Scheduled CodeAuditor Test
  always: true
  branches:
    include:
    - release/*
    exclude:
    - main

stages:
- stage: test
  displayName: Tests - CodeAuditor
  jobs:
  - job: Test
    steps:
    - checkout: none

    - task: Bash@3
      displayName: 'SSW CodeAuditor - Check broken links and performance'
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: 'docker run sswconsulting/codeauditor --token 3c34a549-dfb3-442c-b0e3-45942104a8bf --url https://www.ssw.com.au/rules/ --maxthread 200 --debug'