# This Pipeline refreshes the Rule History Cache

resources:
  repositories:
  - repository: sswrulescontent
    type: github
    endpoint: SSWConsulting
    name:  SSWConsulting/SSW.Rules.Content

trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - checkout: sswrulescontent

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/SSW.Rules/.azure/scripts/create-commits-history.ps1
      arguments: > # Use this to avoid newline characters in multiline string
        -PersonalAccessToken $(PersonalAccessToken)
    displayName: 'Get History Commits of Each Contributor'
