# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pr:
  branches:
    include:
    - release/*
    exclude:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  displayName: build
  jobs:
  - job: cancelPreviousBuilds
  steps:
  - task: PowerShell@2
    inputs:
      filePath: 'templates/cancelPreviousBuilds.ps1'
      arguments: '$(CANCEL_BUILD_USER) $(CANCEL_BUILD_TOKEN) $(CANCEL_BUILD_URL)'
      errorActionPreference: 'continue'
  - job: build
    steps:
    - template: templates/build.yml