# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: Content
    type: github
    endpoint: SSWConsulting
    name: SSWConsulting/SSW.Rules.Content
    ref: $(CONTENT_BRANCH)

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
    - main
    exclude:
    - release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
- stage: build
  displayName: build
  jobs:
  - job: build
    timeoutInMinutes: 90
    steps:
    - template: templates/build.yml
