# This Pipeline refreshes the Rule History Cache

resources:
  repositories:
  - repository: sswrulescontent
    type: github
    endpoint: SSWConsulting
    name:  SSWConsulting/SSW.Rules.Content

trigger:
- none

pr:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - checkout: sswrulescontent

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/SSW.Rules/.azure/scripts/update-rule-history.ps1
      arguments: > 
        -AzFunctionBaseUrl $(AzFunctionBaseUrl)
        -GetHistorySyncCommitHashKey $(GetHistorySyncCommitHashKey)
        -UpdateRuleHistoryKey $(UpdateRuleHistoryKey)
        -UpdateHistorySyncCommitHashKey $(UpdateHistorySyncCommitHashKey)
    displayName: 'Get Rule History Commits'

  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/SSW.Rules/.azure/scripts/update-latest-rules.ps1
      arguments: > 
        -AzFunctionBaseUrl $(AzFunctionBaseUrl)
        -UpdateLatestRulesFunctionKey $(UpdateLatestRulesFunctionKey)
    displayName: 'Update Latest Rules'
