backend:
  name: github
  repo: bradystroud/SSW.Rules.Content
  branch: main
  open_authoring: true

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: rules
    label: Rules
    folder: rules
    media_folder: ''
    public_folder: ''
    slug: 'rule'
    path: '{{uri}}/rule'
    create: true
    fields:
      - { name: guid, label: guid, widget: hidden }
      - { name: type, label: Type (e.g. rule/category), widget: hidden }
      - { name: created, label: Date created, widget: hidden }
      - { name: title, label: Title }
      - { name: uri, label: uri }
      - { name: body, label: Body, widget: markdown }
      - name: authors 
        label: Authors 
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: url, label: url }
      - name: related
        label: Related
        required: false
        widget: list
        field: { name: relatedRule, label: Rule uri, widget: string }
        # field: { name: relatedRule, label: Rule, widget: relation, collection: rules, search_fields: [title], value_field: uri, display_fields: [title], options_length: 5 }
      - { name: archivedreason, label: Archived Reason (leave blank if none), required: false }
  - name: categories
    label: Categories
    folder: categories
    media_folder: ''
    public_folder: ''
    slug: '{{slug}}'
    path: '{{uri}}/index'
    create: true
    fields:
      - { name: type, label: Type (e.g. rule/category), widget: hidden  }
      - { name: guid, label: guid, widget: hidden }
      - { name: title, label: Title }
      - { name: uri, label: uri }
      - { name: index, label: index }