backend:
  name: github
  repo: bradystroud/SSW.Rules.Content
  branch: main
  open_authoring: true

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: rules
    label: Rules
    folder: rules
    media_folder: ''
    public_folder: ''
    slug: 'rule'
    path: '{{uri}}/rule'
    create: true
    fields:
      - { name: type, label: Type (e.g. rule/category), widget: hidden }
      - { name: guid, label: guid, widget: hidden }
      - { name: archivedreason, label: Archived Reason (leave blank if none), required: false }
      - { name: title, label: Title }
      - { name: uri, label: uri }
      - { name: created, label: Date created, widget: datetime}
      - { name: related, label: Related, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: authors, 
          label: Authors,
          widget: list,
          fields: { name: title, label: Title }
                  { name: url, label: url }
        }
      - { name: related,
          label: Related,
          widget: list,
          field: { name: url, label: url, widget: string }
        }
  - name: categories
    label: Categories
    folder: categories
    media_folder: ''
    public_folder: ''
    slug: '{{slug}}'
    path: '{{uri}}/index'
    create: true
    fields:
      - { name: type, label: Type (e.g. rule/category), widget: hidden  }
      - { name: guid, label: guid, widget: hidden }
      - { name: title, label: Title }
      - { name: uri, label: uri }
      - { name: index, label: index }