query latestRulesQuery($size: Float, $sortOption: String) {
  ruleConnection(last: $size, sort: $sortOption) {
    edges {
      node {
        id
        title
        lastUpdated
        lastUpdatedBy
        created
        createdBy
        uri
      }
    }
  }
}

query topCategoryWithIndexQuery($first: Float, $after: String) {
  categoryConnection(first: $first, after: $after) {
    edges {
      node {
        __typename
        ... on CategoryTop_category {
          title
          _sys {
            relativePath
          }
          index {
            category {
              ... on CategoryCategory {
                title
                _sys {
                  filename
                }
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query paginatedTopCategoriesQuery($first: Float, $after: String) {
  categoryConnection(first: $first, after: $after) {
    edges {
      node {
        __typename
        ... on CategoryTop_category {
          title
          _sys {
            filename
          }
          index {
            category {
              ... on CategoryCategory {
                title
                _sys {
                  filename
                }
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}


query categoryWithRulesQuery($relativePath: String!) {
  category(relativePath: $relativePath) {
    ... on CategoryCategory {
      title
      body
      uri
      index {
        rule {
          ... on Rule {
            guid
            uri
            title
            body
          }
        }
      }
    }
  }
}

query rulesByGuidQuery($guids: [String!]!) {
  ruleConnection(filter: { guid: { in: $guids } }) {
    edges {
      node {
        guid
        title
        uri
        body
        authors {
          title
        }
      }
    }
  }
}

query rulesByUriQuery($uris: [String!]!) {
  ruleConnection(filter: { uri: { in: $uris } }) {
    edges {
      node {
        guid
        title
        uri
        body
        authors {
          title
        }
      }
    }
  }
}

query rulesByAuthor($authorTitle: String!) {
  ruleConnection(
    filter: { authors: { title: { eq: $authorTitle } } }
  ) {
    edges {
      node {
        guid
        title
        uri
        body
        authors {
          title
        }
      }
    }
  }
}