name: Staging - build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: staging

jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ github.ref }}
      environment: staging
    secrets: inherit

  deploy:
    needs: build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
    secrets: inherit
