name: Production - build and deploy

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      commit_data:
        description: 'Generate commit data'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no

concurrency:
  group: production

jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ github.ref }}
      environment: production
      commit_data: ${{ github.event.inputs.commit_data }}
    secrets: inherit

  deploy:
    needs:
      - build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: production
    secrets: inherit
