name: Staging - build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        required: false
        type: string
        description: 'The branch to build from (defaults to github.ref_name)'

concurrency:
  group: staging

jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ inputs.branch_name || github.ref_name}}
      environment: staging
    secrets: inherit

  deploy:
    needs: build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
    secrets: inherit
