name: Production - build and deploy

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

concurrency:
  group: production

jobs:

  sync-history:
    name: Sync Rules History
    uses: ./.github/workflows/template-update-rules-history.yml
    with:
      branch_name: ${{ github.ref }}
      environment: production
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ github.ref }}
      environment: production
    secrets: inherit

  deploy:
    needs:
      - build
      - sync-history
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: production
    secrets: inherit
