name: Staging - build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      content_branch:
        type: string
        description: 'Branch to deploy'
        default: 'main'
      should_generate_commit_data:
        type: boolean
        description: 'Generate commit data'
        default: true

jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ github.ref }}
      environment: staging
      should_generate_commit_data: ${{ github.event.inputs.should_generate_commit_data == 'true' }}
      content_branch: ${{ inputs.content_branch }}
    secrets: inherit

  deploy:
    concurrency:
      group: staging-deploy
      cancel-in-progress: false
    needs: build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
    secrets: inherit
