name: Staging - build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      should_generate_commit_data:
        type: boolean
        description: 'Generate commit data'
        default: true

concurrency:
  group: staging

jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: ${{ github.ref }}
      environment: staging
      should_generate_commit_data: ${{ github.event.inputs.should_generate_commit_data }}
    secrets: inherit

  deploy:
    needs: build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
    secrets: inherit
