name: Tina Migration - build and deploy

on:
  push:
    branches:
    - tina/main
  workflow_dispatch:
    inputs:
      should_generate_commit_data:
        type: boolean
        description: 'Generate commit data'
        default: true


jobs:

  build:
    name: Build
    uses: ./.github/workflows/template-build.yml
    with:
      branch_name: tina/main
      environment: staging
      should_generate_commit_data: ${{ 'false' }}
    secrets: inherit

  deploy:
    concurrency:
      group: tina-deploy
      cancel-in-progress: false
    needs: build
    name: Deploy
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
      storageAccountName: 'tina'
    secrets: inherit
