name: PR - Lint code

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.number }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --immutable

      - run: yarn lint --max-warnings 0
