name: Template - Build site

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'The environment to build for'

jobs:
  get-content-commit-data:
    name: Getnerate commit data
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules
        with:
          path: SSW.Rules
          sparse-checkout: |
            build-scripts
            static
          fetch-depth: 1

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules.Content
        with:
          repository: SSWConsulting/SSW.Rules.Content
          path: SSW.Rules.Content
          ref: main
          fetch-depth: 0

      - name: Get Rule History JSON
        shell: pwsh
        run: |
          ./build-scripts/scripts/get-rule-history.ps1 `
            -AzFunctionBaseUrl ${{ vars.AzFunctionBaseUrl }} `
            -GenerateHistoryFileFunctionKey ${{ secrets.GenerateHistoryFileFunctionKey }} `
            -outputFileName "history.json"
      - name: Get History Commits of Each Contributor
        shell: pwsh
        run: |
          ./build-scripts/scripts/create-commits-history.ps1 `
            -Token ${{ secrets.GITHUB_TOKEN }} `
            -GithubOrg ${{ github.repository_owner }} `
            -GithubRepo SSW.Rules.Content
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: commit-data
          path: static/*.json
          retention-days: 1

  build-code:
    name: Gatsby
    runs-on: ubuntu-latest
    needs: get-content-commit-data
    environment: ${{ inputs.environment }}
    env:
      sha: ${{ github.sha }}
    steps:

      - uses: actions/checkout@v4

      - name: Download commit data artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-data
          path: commit-data

      - name: Move commit data
        run: mv commit-data/* static/

      - name: Generate SHA
        run: echo "sha=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        env:
          GITHUB_SHA: ${{ github.sha }}

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: .env.template
        env:
          GOOGLE_ANALYTICS: ${{ vars.GOOGLE_ANALYTICS }}
          VERSION_DEPLOYED: ${{ env.sha }}
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
          CONTENT_BRANCH: ${{ vars.CONTENT_BRANCH }}
          API_BASE_URL: ${{ vars.AZFUNCTIONBASEURL }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          AUTH0_REDIRECT_URI: ${{ vars.AUTH0_REDIRECT_URI }}
          GITHUB_API_PAT: ${{ secrets.GITHUB_TOKEN }}
          DISQUS_FORUM: ${{ vars.DISQUS_FORUM }}
          DISQUS_API_KEY: ${{ secrets.DISQUS_API_KEY }}
          GTM_CONTAINER_ID: ${{ vars.GTM_CONTAINER_ID }}
          GITHUB_ORG: ${{ github.repository_owner }}
          GITHUB_REPO: SSW.Rules.Content
          GATSBY_ALGOLIA_APP_ID: ${{ vars.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - name: Rename env file
        run: |
          mv .env.template .env.production
          cat .env.production

      - name: Cache Gatsby .cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: gatsby_cache | ${{ runner.os }}
          restore-keys: |
            gatsby_cache | ${{ runner.os }}

      - name: Cache Gatsby public
        uses: actions/cache@v4
        with:
          path: public
          key: gatsby_public | ${{ runner.os }}
          restore-keys: |
            gatsby_public | ${{ runner.os }}

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public

  build-infra:
    name: Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            infra

      - name: Check the result
        shell: bash
        run: |
          mkdir arm
          az bicep build --file infra/main.bicep --outdir arm

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: infra

  deploy:
    name: test
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules
        with:
          path: SSW.Rules
          sparse-checkout: |
            build-scripts
            static
          fetch-depth: 1

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload files to Azure storage
        run: |
            azcopy sync \
            ${{ github.workspace }} \
            "https://sarulesstagbbfslamgwndh2.z8.web.core.windows.net/\$web" \
            --recursive \
            --compare-hash MD5 --put-md5 --delete-destination true
