name: Template - Build site

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      environment:
        type: string
        required: true
        description: 'The environment to build for'
      should_generate_commit_data:
        type: boolean
        description: 'Generate commit data for rules history. You might want to skip this on large rules changes.'
        required: true

jobs:
  get-content-commit-data:
    name: Generate commit data
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout SSW.Rules
        with:
          path: SSW.Rules
          ref: ${{ inputs.branch_name }}
          sparse-checkout: |
            build-scripts
          fetch-depth: 1

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules.Content
        with:
          repository: SSWConsulting/SSW.Rules.Content
          path: SSW.Rules.Content
          ref: main
          fetch-depth: 0

      - name: Record the latest SHA for the content repo
        working-directory: SSW.Rules.Content
        run: |
          echo '### Content repo info! 🚀' >> $GITHUB_STEP_SUMMARY
          echo "Latest SHA: [$(git rev-parse HEAD)](https://github.com/SSWConsulting/SSW.Rules.Content/commit/$(git rev-parse HEAD))" >> $GITHUB_STEP_SUMMARY


      - name: Get Rule History Commits
        shell: pwsh
        run: |
          ./SSW.Rules/build-scripts/update-rule-history.ps1 `
            -AzFunctionBaseUrl ${{ vars.AzFunctionBaseUrl }} `
            -GetHistorySyncCommitHashKey ${{ secrets.GETHISTORYSYNCCOMMITHASHFUNCTIONKEY }} `
            -UpdateRuleHistoryKey ${{ secrets.UPDATERULEHISTORYFUNCTIONKEY }} `
            -UpdateHistorySyncCommitHashKey ${{ secrets.UPDATEHISTORYSYNCCOMMITHASHFUNCTIONKEY }} `
            -ShouldGenerateHistory ${{ inputs.should_generate_commit_data }}

      - name: Get Rule History JSON
        shell: pwsh
        run: |
          mkdir static
          ./SSW.Rules/build-scripts/get-rule-history.ps1 `
            -AzFunctionBaseUrl ${{ vars.AzFunctionBaseUrl }} `
            -GenerateHistoryFileFunctionKey ${{ secrets.GenerateHistoryFileFunctionKey }} `
            -outputFileName ${{ github.workspace }}/static/history.json

      - name: Get History Commits of Each Contributor
        shell: pwsh
        run: |
          ./SSW.Rules/build-scripts/create-commits-history.ps1 `
            -Token ${{ secrets.GITHUB_TOKEN }} `
            -GithubOrg ${{ github.repository_owner }} `
            -GithubRepo SSW.Rules.Content `
            -outputFileName ${{ github.workspace }}/static/commits.json
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: commit-data
          path: static
          retention-days: 1

  build-code:
    name: Gatsby
    runs-on: ubuntu-latest
    needs: get-content-commit-data
    environment: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Download commit data artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-data
          path: commit-data

      - name: Move commit data
        run: mv commit-data/* static/

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: .env.template
        env:
          SITE_URL: ${{ vars.SITE_URL }}
          GOOGLE_ANALYTICS: ${{ vars.GOOGLE_ANALYTICS }}
          DEPLOYMENT_URL: https://github.com/SSWConsulting/SSW.Rules/actions/workflows/build-deploy-production.yml
          VERSION_DEPLOYED: ${{ github.run_number }}
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          CONTENT_BRANCH: ${{ vars.CONTENT_BRANCH }}
          API_BASE_URL: ${{ vars.AZFUNCTIONBASEURL }}
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          AUTH0_REDIRECT_URI: ${{ vars.AUTH0_REDIRECT_URI }}
          AUTH0_SCOPE: ${{ vars.AUTH0_SCOPE }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          GITHUB_API_PAT: ${{ secrets.CONTENT_GITHUB_TOKEN }}
          GTM_CONTAINER_ID: ${{ vars.GTM_CONTAINER_ID }}
          GITHUB_ORG: ${{ github.repository_owner }}
          GITHUB_REPO: SSW.Rules.Content
          GATSBY_ALGOLIA_APP_ID: ${{ vars.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GISCUS_REPO_NAME: ${{ secrets.GISCUS_REPO_NAME }}
          GISCUS_REPO_ID: ${{ secrets.GISCUS_REPO_ID }}
          GISCUS_CATEGORY_ID: ${{ secrets.GISCUS_CATEGORY_ID }}
          GISCUS_THEME_URL: ${{ secrets.GISCUS_THEME_URL }}
          CRM_APP_ID: ${{ secrets.CRM_APP_ID }}
          CRM_TENANT: ${{ secrets.CRM_TENANT }}
          CRM_TENANT_ID: ${{ secrets.CRM_TENANT_ID }}
          CRM_APP_SECRET: ${{ secrets.CRM_APP_SECRET }}
          CRM_SCOPE: ${{ secrets.CRM_SCOPE }}
          CRM_VIEW_CURRENT: ${{ secrets.CRM_VIEW_CURRENT }}
          CRM_VIEW_PAST: ${{ secrets.CRM_VIEW_PAST }}

      - name: Rename env file
        run: |
          mv .env.template .env.production
          cat .env.production

      - name: Cache Gatsby .cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: gatsby_cache | ${{ runner.os }}
          restore-keys: |
            gatsby_cache | ${{ runner.os }}

      - name: Cache Gatsby public
        uses: actions/cache@v4
        with:
          path: public
          key: gatsby_public | ${{ runner.os }}
          restore-keys: |
            gatsby_public | ${{ runner.os }}

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        timeout-minutes: 30

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public

  build-infra:
    name: Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}
          sparse-checkout: |
            infra

      - name: Check the result
        shell: bash
        run: |
          mkdir arm
          az bicep build --file infra/main.bicep --outdir arm

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: infra
