name: Template - Build site

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      environment:
        type: string
        required: true
        description: 'The environment to build for'
      should_generate_commit_data:
        type: boolean
        description: 'Generate commit data for rules history. You might want to skip this on large rules changes.'
        required: false
        default: true

jobs:
  get-content-commit-data:
    name: Generate commit data
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules
        with:
          path: SSW.Rules
          ref: ${{ inputs.branch_name }}
          sparse-checkout: |
            build-scripts
          fetch-depth: 1

      - uses: actions/checkout@v4
        name: Checkout SSW.Rules.Content
        with:
          repository: SSWConsulting/SSW.Rules.Content
          path: SSW.Rules.Content
          ref: main
          fetch-depth: 0

      - name: Record the latest SHA for the content repo
        working-directory: SSW.Rules.Content
        run: |
          echo '### Content repo info! 🚀' >> $GITHUB_STEP_SUMMARY
          echo "Latest SHA: [$(git rev-parse HEAD)](https://github.com/SSWConsulting/SSW.Rules.Content/commit/$(git rev-parse HEAD))" >> $GITHUB_STEP_SUMMARY


      - name: Get Rule History Commits
        shell: pwsh
        run: |
          ./SSW.Rules/build-scripts/update-rule-history.ps1 `
            -AzFunctionBaseUrl ${{ vars.AzFunctionBaseUrl }} `
            -GetHistorySyncCommitHashKey ${{ secrets.GETHISTORYSYNCCOMMITHASHFUNCTIONKEY }} `
            -UpdateRuleHistoryKey ${{ secrets.UPDATERULEHISTORYFUNCTIONKEY }} `
            -UpdateHistorySyncCommitHashKey ${{ secrets.UPDATEHISTORYSYNCCOMMITHASHFUNCTIONKEY }} `
            -ShouldGenerateHistory ${{ inputs.should_generate_commit_data }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: commit-data
          path: static
          retention-days: 1
